### ISSUE TITLE
AuthFailure

### ISSUE THREAD

**Issue by laroy-sh** [disruptops/resource-counter#2]
Hi, Rich. Any ideas why I'm getting this (fresh Kali 19.2)?
Of course, the credentials are correct, doublechecked, and permissions are "readonlyaccess" + "securityaudit".
Thanks in advance!

`Establishing AWS session using the profile- xxxxx
Current account ID: 11111
Counting resources across regions. This will take a few minutes...

Traceback (most recent call last):
  File "count_resources.py", line 430, in <module>
    controller()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "count_resources.py", line 59, in controller
    ec2_counter(account_id)
  File "count_resources.py", line 125, in ec2_counter
    endpoints = ec2client.describe_vpc_endpoints()
  File "/home/ec2-user/.local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the DescribeVpcEndpoints operation: AWS was not able to validate the provided access credentials
`

**Comment by romansinelnikov** [comment]
It is bug in boto3 https://github.com/boto/boto3/issues/2022
a temporary fix: use old version 1.9.135

**Comment by cristiannoguera** [comment]
Me pasaba el mismo problema.
Realice el cambio por la versión 1.9.135 del boto3 boto/boto3 #1572 y funciona correctamente.

**Comment by MeghP** [comment]
I still get the same error even after downgrading boto3 to version 1.9.135

Error:

Counting resources across regions. This will take a few minutes...
 
Traceback (most recent call last):
  File "resourceCount.py", line 431, in <module>
    controller()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "resourceCount.py", line 60, in controller
    ec2_counter(account_id)
  File "resourceCount.py", line 126, in ec2_counter
    endpoints = ec2client.describe_vpc_endpoints()
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the DescribeVpcEndpoints operation: AWS was not able to validate the provided access credentials

**Comment by cristiannoguera** [comment]
> Todavía recibo el mismo error incluso después de degradar boto3 a la versión 1.9.135
> 
> Error:
> 
> Contando recursos entre regiones. Esto tomará unos pocos minutos...
> 
> Rastreo (última llamada más reciente):
> archivo "resourceCount.py", línea 431, en el
> controlador ()
> Archivo "/usr/local/lib/python2.7/dist-packages/click/core.py", línea 764, en **call**
> return self.main (* args, ** kwargs)
> Archivo "/usr/local/lib/python2.7/dist-packages/click/core.py", línea 717, en la línea principal
> rv = self.invoke (ctx)
> Archivo "/usr/local/lib/python2.7/dist-packages/click/core.py", línea 956, en
> invoke return ctx.invoke (self.callback, ** ctx.params)
> Archivo "/ usr / local /lib/python2.7/dist-packages/click/core.py ", línea 555, en invoke
> return callback (* args, ** kwargs)
> Archivo" resourceCount.py ", línea 60, en el controlador
> ec2_counter (account_id)
> Archivo "resourceCount.py ", línea 126, en ec2_counter
> puntos finales = ec2client.describe_vpc_endpoints ()
> Archivo "/usr/local/lib/python2.7/dist-packages/botocore/client.py", línea 357, en _api_call
> return self._make_api_call (nombre_operación, kwargs)
> Archivo "/ usr / local / lib / python2.7 / dist-packages / botocore / client.py ", línea 661, en _make_api_call
> raise error_class (parsed_response, operation_name)
> botocore.exceptions.ClientError: Se produjo un error (AuthFailure) al llamar a la operación DescribeVpcEndpoints: AWS no pudo validar las credenciales de acceso proporcionadas

De mi parte me funcionó perfectamente después de degradar el boto3 

pip install -U botocore==1.12.135 boto3==1.9.135

**Comment by MeghP** [comment]
Eso me funcionó a mí también.
Gracias

**Comment by c0decave** [comment]
Opened up pull request which should fix the major issues. Otherwise give this version here a shot:
https://github.com/c0decave/resource-counter
